name: morening_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  audioplayers: ^6.1.0
  alarm: ^4.0.12
  slide_to_act: ^2.0.2
  permission_handler: ^11.3.1
  intl: ^0.20.1
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ringtones/
    - assets/terms_of_agreement.txt

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
