name: morening_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  audioplayers: ^6.1.0
  alarm: ^4.0.12
  slide_to_act: ^2.0.2
  permission_handler: ^11.3.1
  auto_start_flutter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ringtones/
