name: morening_2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3
  flutter_fgbg: ^0.6.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  amplify_flutter: ^1.8.0
  amplify_auth_cognito: ^1.7.0
  intl: ^0.20.0
  alarm: ^4.1.1
  dio: ^5.7.0
  wifi_iot: ^0.3.19+1
  wifi_scan: ^0.4.1+1
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ringtones/
    - assets/terms_of_agreement.txt

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
